### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [marutichintan/pymssql#12]
```
Since 2.7 now appears to be Python's "official" version I'm really hoping you 
guys can get out a version for it soon.
```

Original issue reported on code.google.com by `vidarlun...@gmail.com` on 14 Jul 2010 at 6:23

**Comment by GoogleCodeExporter** [comment]
```
Do you mean Windows binaries?
```

Original comment by `akuk...@gmail.com` on 21 Sep 2010 at 2:06
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Yes
```

Original comment by `vidarlun...@gmail.com` on 21 Sep 2010 at 6:05

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I've build 2.7 binaries (haven't tested yet), will attach.
```

Original comment by `mes...@gmail.com` on 2 Nov 2010 at 5:52

Attachments:
- [pymssql27.zip](https://storage.googleapis.com/google-code-attachments/pymssql/issue-12/comment-4/pymssql27.zip)

**Comment by GoogleCodeExporter** [comment]
```
hi guys, is this stable? anybody tested it?
```

Original comment by `martin.g...@gmail.com` on 25 Nov 2010 at 8:43

**Comment by GoogleCodeExporter** [comment]
```
people, how do i install pymssql on windows with python 2.7?
```

Original comment by `Koole...@gmail.com` on 12 Jan 2011 at 7:24

**Comment by GoogleCodeExporter** [comment]
```
Hello guys, i need pymssql for python 2.7 too!! i'll try tested your binaries
```

Original comment by `pseude...@gmail.com` on 14 Jan 2011 at 10:01

**Comment by GoogleCodeExporter** [comment]
```
Binaries seem to work, thanks! Is there any chance to 'officially' roll this 
out?
```

Original comment by `alexodon...@gmail.com` on 10 Feb 2011 at 2:43

**Comment by GoogleCodeExporter** [comment]
```
Binaries don't work for me. I get an error on loading the dll included. I'm 
running ActivePython 2.7 x64, wondering if you just compiled the x32?
```

Original comment by `michael....@gmail.com` on 15 Feb 2011 at 4:56

**Comment by GoogleCodeExporter** [comment]
```
How do I install this?
```

Original comment by `bytew...@gmail.com` on 19 Feb 2011 at 11:17

**Comment by GoogleCodeExporter** [comment]
```
I have been building snapshots here, 
http://build.damoxc.net/downloads/pymssql/snapshots/ however I can't comment on 
their stability and also if memory serves I'm fairly sure you need to pass an 
environment variable specifying where the freetds.conf file is. I need to work 
out how to avoid requiring that file ideally.
```

Original comment by `dam...@gmail.com` on 27 Mar 2011 at 2:44

**Comment by GoogleCodeExporter** [comment]
```
isn't it about time for a official 2.7 release?  The snapshots in the last post 
do not work.
```

Original comment by `tony.cad...@gmail.com` on 29 Jul 2011 at 6:22

**Comment by GoogleCodeExporter** [comment]
```
Tony,

Yes, but there is only so much time in the day and there are still a few bugs 
to be ironed out.  The current HG tip works on 2.7, you are welcome to build it.
```

Original comment by `rsyr...@gmail.com` on 30 Jul 2011 at 6:27

**Comment by GoogleCodeExporter** [comment]
```
I need a working windows version for python 2.7. Don't know exactly how to 
build, but i can spend time to learn and do it. If someone could explain me, i 
could build for all python 2.x version and test them.

thanks.
```

Original comment by `arakim...@gmail.com` on 28 Aug 2011 at 10:03

**Comment by GoogleCodeExporter** [comment]
```
requiring a version of python before it can install seems silly. most 
everything i have seen in python 2.x series has been backward compatible. am i 
wrong? the installation seems to be checking for 2.6 in the registry. 
sqlalchemy, here i come! pymssql was great when i used it before. i guess 
momentum for this project has halted ?
```

Original comment by `davidj...@gmail.com` on 9 Sep 2011 at 6:38

**Comment by GoogleCodeExporter** [comment]
```
SQLAlchemy and pymssql are not the same thing.  You need a SQL Server "driver" 
for SQLAlchemy.  The only two I know of that exist is pymssql and pyodbc.  
Momentum is definitely slow, but not halted.
```

Original comment by `rsyr...@gmail.com` on 19 Sep 2011 at 1:17

**Comment by GoogleCodeExporter** [comment]
```
The HG tip works in 2.7 but it does result in a few warnings... 

cythoning _mssql.pyx to _mssql.c
warning: _mssql.pyx:1198:51: local variable 'data' referenced before assignment
warning: _mssql.pyx:170:11: Unreachable code
building '_mssql' extension

cythoning pymssql.pyx to pymssql.c
warning: pymssql.pyx:410:8: Unreachable code
building 'pymssql' extension

```

Original comment by `rizw...@gmail.com` on 4 Oct 2011 at 5:34

**Comment by GoogleCodeExporter** [comment]
```
if this is not the place for this , tell me where to give feedback please:
tried 2 methods to install:

C:\Python\27\Scripts>easy_install.exe pymssql
Searching for pymssql
Reading http://pypi.python.org/simple/pymssql/
Reading http://code.google.com/p/pymssql/
Reading http://code.google.com/p/pymssql/downloads/list
Reading http://pymssql.sourceforge.net
Reading 
http://sourceforge.net/project/showfiles.php?group_id=40059&package_id=32202
Best match: pymssql 1.9.908.win32
Downloading http://pymssql.googlecode.com/files/pymssql-1.9.908.win32.zip
Processing pymssql-1.9.908.win32.zip
error: Couldn't find a setup script in 
c:\docume~1\djacks~1\locals~1\temp\easy_install-gba42y\pymssql-1.9.908.win32.zip

2nd method 
cythoning _mssql.pyx to _mssql.c
building '_mssql' extension
C:\Program Files\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD 
/W3 /GS- /DNDEBUG -Iwin32\freetds\include -Ic:\Python\27\include 
-Ic:\Python\27\PC /Tc_mssql.c /Fobuild\temp.win32-2.7\Release\_mssql.obj 
-DMSDBLIB
_mssql.c
_mssql.c(1) : fatal error C1189: #error :  Do not use this file, it is the 
result of a failed Cython compilation.

how to resolve the failed Cython compilation?

```

Original comment by `davidj...@gmail.com` on 5 Oct 2011 at 3:18

**Comment by GoogleCodeExporter** [comment]
```
If you want a working version, you are going to have to use HG tip.  
easy_install is not currently going to work.
```

Original comment by `rsyr...@gmail.com` on 6 Oct 2011 at 7:58

**Comment by GoogleCodeExporter** [comment]
```
pyodbc ended up being a good solution - no clue if there was any tradeoff to 
performance or something else.

what is HG tip? google makes me think it is a development term. 

```

Original comment by `davidj...@gmail.com` on 7 Oct 2011 at 2:56

**Comment by GoogleCodeExporter** [comment]
```
Anyone could explain what HG tip is? I'm really confused about this term.
Installing pymssql with python 2.7 failed with following error message:

cl:Command line error D8021: invalid numeric argument 
'-Wl,-allow-multiple-definition'
I'm using Visual C++ 2008 Express Edition


```

Original comment by `gbstac...@gmail.com` on 3 Nov 2011 at 3:55

**Comment by GoogleCodeExporter** [comment]
```
"hg tip" is Mercurial version control speak
```

Original comment by `agui...@gmail.com` on 3 Nov 2011 at 10:08

**Comment by GoogleCodeExporter** [comment]
```
latest HG tip will support 2.7 I believe, although we don't have binaries for 
it yet, that issues is tracked elsewhere.
```

Original comment by `rsyr...@gmail.com` on 8 Mar 2012 at 3:00
- Changed state: **Duplicate**

**Comment by GoogleCodeExporter** [comment]
```
Does the python 2.7 windows installer at the bottom of this page work?

http://code.google.com/p/pymssql/issues/detail?id=54


```

Original comment by `geo...@ringdevelopment.com` on 15 Jun 2012 at 3:04
